"""PKCE (Proof Key for Public Clients) support.

PKCE prevents authorization code interception attacks by requiring clients
to prove they are the same entity that issued the authorization request.
"""

import base64
import hashlib
import secrets


def generate_code_challenge(code_verifier: str, method: str = "S256") -> str:
    """Generate a PKCE code challenge from a verifier.

    Args:
        code_verifier: The code verifier string (generated by client).
        method: Challenge method: 'S256' (SHA256, recommended) or 'plain'.

    Returns:
        Code challenge string.

    Raises:
        ValueError: If method is not recognized.
    """
    if method == "S256":
        # Hash the verifier and base64url-encode it
        digest = hashlib.sha256(code_verifier.encode("ascii")).digest()
        challenge = base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")
        return challenge
    elif method == "plain":
        return code_verifier
    else:
        raise ValueError(f"Unsupported PKCE method: {method}")


def verify_pkce(
    code_verifier: str,
    code_challenge: str,
    code_challenge_method: str,
) -> bool:
    """Verify a PKCE code verifier against the stored challenge.

    Args:
        code_verifier: The verifier provided in the token request.
        code_challenge: The challenge stored from the authorization request.
        code_challenge_method: The method used to generate the challenge.

    Returns:
        True if verifier is valid for this challenge, False otherwise.
    """
    try:
        computed_challenge = generate_code_challenge(code_verifier, code_challenge_method)
        return computed_challenge == code_challenge
    except ValueError:
        return False


def generate_code_verifier() -> str:
    """Generate a random PKCE code verifier for use by clients.

    Code verifier is 43-128 characters of unreserved characters [A-Z] [a-z] [0-9] - . _ ~

    Used by development clients to generate PKCE parameters.

    Returns:
        Random code verifier string (43 characters).
    """
    # Generate 32 random bytes and base64url-encode
    random_bytes = secrets.token_bytes(32)
    verifier = base64.urlsafe_b64encode(random_bytes).decode("ascii").rstrip("=")
    return verifier
