name: Deploy with podman compose

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: innovation
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: write marker
        run: echo "yes" > should_deploy_job.txt
